INSERT INTO configuracoes (chave, valor, tipo, categoria, descricao) VALUES
('nome_sistema','{{NOME_SISTEMA}}','texto','geral','Nome do sistema'),
('slogan','{{SLOGAN}}','texto','geral','Slogan'),
('valor_titulo','10','numero','geral','Valor de cada título'),
('premio_principal','120000','numero','geral','Prêmio principal'),
('canal_sorteio','{{CANAL_SORTEIO}}','texto','geral','Canal de transmissão'),
('cor_primaria','{{COR_PRIMARIA}}','cor','cores','Cor principal'),
('cor_secundaria','{{COR_SECUNDARIA}}','cor','cores','Cor secundária'),
('cor_primaria_escura','{{COR_PRIMARIA_ESCURA}}','cor','cores','Cor primária escura'),
('cor_fundo_site','#F5F7FA','cor','cores','Fundo do site'),
('cor_fundo_hero','{{COR_PRIMARIA}}','cor','cores','Fundo do hero'),
('cor_texto_hero','#FFFFFF','cor','cores','Texto do hero'),
('dash_cor_sidebar','{{COR_PRIMARIA_ESCURA}}','cor','dashboard','Cor sidebar'),
('dash_cor_header','{{COR_PRIMARIA}}','cor','dashboard','Cor header'),
('logo_url','/logo.png','imagem','midias','Logo principal'),
('favicon_url','/logo.png','imagem','midias','Favicon'),
('fundo_hero_url','/fundo.png','imagem','midias','Fundo hero desktop'),
('fundo_hero_mobile_url','','imagem','midias','Fundo hero mobile'),
('banner_sorteio_url','','imagem','midias','Banner sorteio'),
('banner_compra_url','','imagem','midias','Banner compra'),
('cartela_imagem_url','','imagem','midias','Imagem cartela'),
('email_suporte','{{EMAIL_SUPORTE}}','texto','contato','Email suporte'),
('whatsapp_suporte','{{WHATSAPP}}','texto','contato','WhatsApp'),
('instagram_url','','texto','contato','Instagram'),
('facebook_url','','texto','contato','Facebook'),
('rodape_texto','Título de Capitalização nº XXXX/XXXX SUSEP','texto','rodape','Texto rodapé'),
('rodape_direitos','2026 {{NOME_SISTEMA}}. Todos os direitos reservados.','texto','rodape','Direitos'),
('sobre_titulo','Sorteios que transformam vidas','texto','sobre','Título sobre'),
('sobre_texto','Um título de capitalização filantrópico.','texto','sobre','Texto sobre'),
('sobre_hospital','{{HOSPITAL_PARCEIRO}}','texto','sobre','Hospital parceiro'),
('sobre_titulos_edicao','100.000','texto','sobre','Títulos por edição'),
('passo_1_titulo','Escolha seu título','texto','como_participar','Passo 1'),
('passo_1_texto','Selecione a quantidade de títulos desejada','texto','como_participar','Passo 1 desc'),
('passo_2_titulo','Faça o pagamento','texto','como_participar','Passo 2'),
('passo_2_texto','Pague via PIX de forma rápida e segura','texto','como_participar','Passo 2 desc'),
('passo_3_titulo','Aguarde o sorteio','texto','como_participar','Passo 3'),
('passo_3_texto','Acompanhe ao vivo toda semana','texto','como_participar','Passo 3 desc'),
('passo_4_titulo','Receba seu prêmio','texto','como_participar','Passo 4'),
('passo_4_texto','Prêmio pago via PIX instantâneo','texto','como_participar','Passo 4 desc'),
('sorteio_titulo','Sorteio da Semana','texto','sorteio','Título sorteio'),
('sorteio_dia_semana','Toda sexta-feira','texto','sorteio','Dia sorteio'),
('sorteio_horario','21h00','texto','sorteio','Horário sorteio'),
('seo_titulo','{{NOME_SISTEMA}} - Filantropia Premiável','texto','seo','Título SEO'),
('seo_descricao','Concorra a prêmios e ajude instituições beneficentes','texto','seo','Meta description'),
('hero_titulo','{{NOME_SISTEMA}}','texto','hero','Título hero'),
('hero_badge','Sorteio toda semana','texto','hero','Badge hero'),
('hero_subtitulo','{{SLOGAN}}','texto','hero','Subtítulo hero'),
('texto_btn_principal','Quero participar →','texto','hero','Botão principal'),
('texto_btn_secundario','Ver sorteio','texto','hero','Botão secundário')
ON CONFLICT (chave) DO NOTHING;

INSERT INTO edicoes (numero, descricao, data_sorteio, hora_sorteio, valor_unitario, total_cartelas, status, premio_principal)
VALUES (1, 'Edição 1', CURRENT_DATE + 7, '21:00:00', 10, 100000, 'rascunho', 120000);
